### ISSUE TITLE
Package license file

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scons-feedstock#15]
Currently the license file is not being included in Conda packages. Would be good to add `license_file` to `about` with the name of the license file in the source distribution so that it gets packaged.

xref: https://github.com/conda-forge/scons-feedstock/pull/14#issuecomment-599302168

**Comment by stuertz** [comment]
The package distributed via pypi does not contain any license information.
see https://github.com/SCons/scons/issues/3598
